// Adaptive space-filling curve (Hilbert / Peano) halftoning.
//
// A space-filling curve threads a single unbroken line through the image. A
// uniform curve carries no tone — so instead of drawing it at a fixed order, we
// vary its depth *locally*: dark cells subdivide further (laying down more line
// per unit area) while light cells stop early (sparse, coarse line). The eye
// reassembles a continuous gradient out of the varying line density, and because
// the whole thing is one continuous curve it is the ideal pen-plotter / CNC
// toolpath — the machine never lifts.
//
// Two curves are offered, both generated by the same adaptive recursion:
//
//   - Hilbert — 2×2 subdivision, no axis crossings, locally compact;
//   - Peano   — 3×3 serpentine subdivision, denser and more woven.
//
// Tone is encoded as subdivision depth: at each cell we sample the local
// darkness and keep recursing while the cell is darker than a level-dependent
// threshold (deeper levels demand darker tone), bounded by a max depth. Leaves
// emit their centre point; consecutive leaves are always spatial neighbours, so
// the centres chain into one continuous path. An optional corner radius fillets
// every vertex into a smooth quadratic, turning the angular lattice into flowing
// curves.
//
// Three rendering Methods let you compare the standard plotter techniques for
// keeping such a curve clean across cells of differing size:
//
//   - Anchor (default) — the plain adaptive curve. It is already continuous
//     because the recursion preserves each cell's entry/exit corners (fixed
//     boundary anchoring), so consecutive leaf centres always chain.
//   - Weld — same adaptive curve, but the diagonal seam between two leaves of
//     different depth is replaced by an orthogonal L-bridge (two axis-aligned
//     segments), welding the join onto the cell grid like a plotter would.
//   - Riemersma — abandons adaptive sizing: lay a *uniform* max-order curve over
//     the whole frame and pen-down only where the tone is dark, carrying the
//     quantisation error forward along the 1-D curve. The geometry stays pristine
//     but the path deliberately breaks (pen lifts) over light areas.

import type { ControlDef, Strategy, StrategyInput } from "./types";

const CONTROLS: ControlDef[] = [
    { key: "base", label: "Base", kind: "slider", min: 1, max: 4, step: 1, default: 2, format: (v) => `L${v}` },
    { key: "detail", label: "Detail", kind: "slider", min: 2, max: 7, step: 1, default: 5, format: (v) => `L${v}` },
    { key: "round", label: "Round", kind: "slider", min: 0, max: 0.5, step: 0.02, default: 0.3, format: (v) => v.toFixed(2) },
    { key: "lineWidth", label: "Weight", kind: "slider", min: 0.3, max: 2, step: 0.1, default: 0.8, format: (v) => v.toFixed(1) },
    { key: "contrast", label: "Contrast", kind: "slider", min: 0.5, max: 2.5, step: 0.1, default: 1.2, format: (v) => v.toFixed(1) },
    {
        key: "method",
        label: "Method",
        kind: "select",
        min: 0,
        max: 2,
        step: 1,
        default: 0,
        options: ["Anchored", "Welded", "Riemersma"],
    },
    { key: "peano", label: "Peano", kind: "toggle", min: 0, max: 1, step: 1, default: 0 },
    { key: "invert", label: "Invert", kind: "toggle", min: 0, max: 1, step: 1, default: 0 },
];

function clamp01(n: number) {
    return n < 0 ? 0 : n > 1 ? 1 : n;
}

// Peano (3×3) recursion uses 9× the cells of Hilbert (2×2) per level, so its
// useful depth is far shallower; clamp it to keep the path machine-sane.
const MAX_DEPTH = { hilbert: 7, peano: 5 } as const;
// Hard cap on plotted points so an extreme detail level can't explode the file.
const MAX_POINTS = 70000;

function render(input: StrategyInput, params: Record<string, number>): string {
    const { width: W, height: H, sample } = input;

    const method = Math.round(params.method ?? 0); // 0 = Anchor, 1 = Weld, 2 = Riemersma
    const peano = (params.peano ?? 0) > 0.5;
    const minDepth = Math.max(1, Math.round(params.base ?? 2));
    const maxCap = peano ? MAX_DEPTH.peano : MAX_DEPTH.hilbert;
    const maxDepth = Math.min(maxCap, Math.max(minDepth + 1, Math.round(params.detail ?? 5)));
    const round = Math.min(0.5, Math.max(0, params.round ?? 0.3));
    const lineWidth = params.lineWidth ?? 0.8;
    const contrast = params.contrast ?? 1.2;
    const invert = (params.invert ?? 0) > 0.5;

    // Darkness in 0..1 where larger = "more ink". Contrast pivots around mid
    // grey; invert flips which side of the tone range reads as dark. Points
    // outside the image read as light so the curve stays coarse there.
    const darknessAt = (x: number, y: number): number => {
        if (x < 0 || x > W || y < 0 || y > H) return 0;
        let l = sample(x, y);
        l = clamp01(0.5 + (l - 0.5) * contrast);
        if (invert) l = 1 - l;
        return 1 - l;
    };

    // Should a cell at `level` keep subdividing? Always reach the base grid;
    // never pass the max. Between them, deeper levels demand a darker cell: the
    // threshold ramps from low (near base) to high (near max), so only the
    // darkest cells subdivide all the way down. Riemersma instead wants a
    // *uniform* curve, so it recurses to the max depth everywhere, ignoring tone.
    const span = maxDepth - minDepth + 1;
    const uniform = method === 2;
    const pts: number[] = [];
    const shouldSubdivide = (cx: number, cy: number, level: number): boolean => {
        if (level >= maxDepth || pts.length >= MAX_POINTS * 2) return false;
        if (uniform) return true;
        if (level < minDepth) return true;
        const threshold = (level - minDepth + 1) / (span + 1);
        return darknessAt(cx, cy) >= threshold;
    };

    // Hilbert curve (2×2), vector form: a cell is an origin (x0,y0) plus an i
    // vector (xi,xj) and a j vector (yi,yj). The four children are visited in
    // Hilbert order, each carrying a rotated/reflected basis so the sub-curves
    // chain end-to-end. A leaf emits its centre point.
    const hilbert = (x0: number, y0: number, xi: number, xj: number, yi: number, yj: number, level: number): void => {
        const cx = x0 + (xi + yi) / 2;
        const cy = y0 + (xj + yj) / 2;
        if (!shouldSubdivide(cx, cy, level)) {
            pts.push(cx, cy);
            return;
        }
        const xi2 = xi / 2;
        const xj2 = xj / 2;
        const yi2 = yi / 2;
        const yj2 = yj / 2;
        hilbert(x0, y0, yi2, yj2, xi2, xj2, level + 1);
        hilbert(x0 + xi2, y0 + xj2, xi2, xj2, yi2, yj2, level + 1);
        hilbert(x0 + xi2 + yi2, y0 + xj2 + yj2, xi2, xj2, yi2, yj2, level + 1);
        hilbert(x0 + xi2 + yi, y0 + xj2 + yj, -yi2, -yj2, -xi2, -xj2, level + 1);
    };

    // Peano curve (3×3), reflection-flag form derived from Peano's closed-form
    // ternary mapping. The nine subcells are visited in a serpentine (t = 0..8);
    // `rx`/`ry` track which axes are currently reflected and propagate to each
    // child so consecutive subcells stay edge-adjacent. The axis vectors keep a
    // fixed direction — orientation lives entirely in the flags.
    const peanoStep = (
        ox: number,
        oy: number,
        ax: number,
        ay: number,
        bx: number,
        by: number,
        level: number,
        rx: number,
        ry: number,
    ): void => {
        const cx = ox + (ax + bx) / 2;
        const cy = oy + (ay + by) / 2;
        if (!shouldSubdivide(cx, cy, level)) {
            pts.push(cx, cy);
            return;
        }
        const a3x = ax / 3;
        const a3y = ay / 3;
        const b3x = bx / 3;
        const b3y = by / 3;
        for (let t = 0; t < 9; t++) {
            const t1 = (t / 3) | 0;
            const t2 = t % 3;
            const col = rx ? 2 - t1 : t1;
            const row = (t1 & 1) ^ ry ? 2 - t2 : t2;
            peanoStep(
                ox + col * a3x + row * b3x,
                oy + col * a3y + row * b3y,
                a3x,
                a3y,
                b3x,
                b3y,
                level + 1,
                rx ^ (t2 & 1),
                ry ^ (t1 & 1),
            );
        }
    };

    if (peano) {
        peanoStep(0, 0, W, 0, 0, H, 0, 0, 0);
    } else {
        hilbert(0, 0, W, 0, 0, H, 0);
    }

    const stroke = invert ? "#ffffff" : "#111111";

    const f = (n: number) => n.toFixed(1);

    let body: string;
    if (method === 2) {
        // Riemersma: walk the uniform curve in order and pen-down only where the
        // running tone (cell darkness + the error carried forward from earlier
        // cells) clears the half-way mark; the quantisation error diffuses along
        // the 1-D path so average tone is preserved. A pen-up breaks the path, so
        // dark runs become separate subpaths and an isolated dark cell renders as
        // a single round-capped dot. The geometry stays a pristine uniform curve.
        let d = "";
        let err = 0;
        let penDown = false;
        for (let i = 0; i < pts.length; i += 2) {
            const x = pts[i];
            const y = pts[i + 1];
            const a = darknessAt(x, y) + err;
            if (a >= 0.5) {
                err = a - 1;
                d += penDown ? ` L ${f(x)} ${f(y)}` : `M ${f(x)} ${f(y)}`;
                penDown = true;
            } else {
                err = a;
                penDown = false;
            }
        }
        body = d ? `<path d="${d}"/>` : "";
    } else {
        // Anchor draws the leaf centres as-is. Weld first replaces every diagonal
        // seam — a move with both a horizontal and a vertical component, which
        // arises where two neighbouring leaves sit at different depths — with an
        // orthogonal L-bridge (longer leg first), stepping the join onto the
        // shared cell wall the way a plotter routes along the grid.
        let draw = pts;
        if (method === 1) {
            const welded: number[] = pts.length ? [pts[0], pts[1]] : [];
            for (let i = 2; i < pts.length; i += 2) {
                const cx = pts[i - 2];
                const cy = pts[i - 1];
                const nx = pts[i];
                const ny = pts[i + 1];
                if (cx !== nx && cy !== ny) {
                    if (Math.abs(ny - cy) >= Math.abs(nx - cx)) welded.push(cx, ny);
                    else welded.push(nx, cy);
                }
                welded.push(nx, ny);
            }
            draw = welded;
        }

        const n = draw.length / 2;
        if (n < 2) {
            body = "";
        } else if (round <= 0 || n < 3) {
            // Sharp lattice — a plain polyline is the most compact encoding.
            const coords: string[] = [];
            for (let i = 0; i < draw.length; i += 2) coords.push(`${f(draw[i])},${f(draw[i + 1])}`);
            body = `<polyline points="${coords.join(" ")}"/>`;
        } else {
            // Filleted corners: cut back from each interior vertex along both edges
            // by `round`× the shorter neighbouring segment, then round the corner
            // with a quadratic through the original vertex. `round` ≤ 0.5 keeps the
            // cuts inside each segment so adjacent fillets never overlap.
            let d = `M ${f(draw[0])} ${f(draw[1])}`;
            for (let i = 1; i < n - 1; i++) {
                const px = draw[2 * i];
                const py = draw[2 * i + 1];
                const v1x = px - draw[2 * i - 2];
                const v1y = py - draw[2 * i - 1];
                const v2x = draw[2 * i + 2] - px;
                const v2y = draw[2 * i + 3] - py;
                const l1 = Math.hypot(v1x, v1y);
                const l2 = Math.hypot(v2x, v2y);
                if (l1 < 1e-3 || l2 < 1e-3) {
                    d += ` L ${f(px)} ${f(py)}`;
                    continue;
                }
                const c = round * Math.min(l1, l2);
                const ex = px - (v1x / l1) * c;
                const ey = py - (v1y / l1) * c;
                const lx = px + (v2x / l2) * c;
                const ly = py + (v2y / l2) * c;
                d += ` L ${f(ex)} ${f(ey)} Q ${f(px)} ${f(py)} ${f(lx)} ${f(ly)}`;
            }
            d += ` L ${f(draw[2 * (n - 1)])} ${f(draw[2 * (n - 1) + 1])}`;
            body = `<path d="${d}"/>`;
        }
    }

    return (
        `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}">` +
        `<g stroke="${stroke}" stroke-width="${lineWidth}" stroke-linecap="round" stroke-linejoin="round" fill="none">` +
        body +
        `</g></svg>`
    );
}

export const hilbertStrategy: Strategy = {
    id: "hilbert",
    label: "Hilbert / Peano Curve",
    controls: CONTROLS,
    render,
};
