// Concentric spiral / rings: a single line wound out from the image centre,
// reproducing tone by deforming its own path instead of by adding more ink.
// Darkness is encoded two ways, both driven by the local sample:
//
//   - wiggle   — darker pixels push the path further off its smooth radius and
//                (for the spiral) tighten the oscillation, so dark regions read
//                as jagged, busy bands while light regions stay near-circular;
//   - compress — darker pixels shrink the local pitch, so successive turns pack
//                closer together and lay down more line per unit area.
//
// The path is generated by integrating outward from the centre: at each step we
// sample the tone under the current point, advance the radius by the (possibly
// compressed) local pitch, and offset the plotted radius by the wiggle. A toggle
// swaps the continuous spiral for a stack of closed concentric rings; rings keep
// a fixed cycle count per revolution so the wiggle closes seamlessly.

import type { ControlDef, Strategy, StrategyInput } from "./types";

const CONTROLS: ControlDef[] = [
    { key: "spacing", label: "Pitch", kind: "slider", min: 4, max: 30, step: 1, default: 10, format: (v) => `${v}px` },
    { key: "amplitude", label: "Wobble", kind: "slider", min: 0, max: 12, step: 0.5, default: 4, format: (v) => `${v}px` },
    { key: "frequency", label: "Wiggle", kind: "slider", min: 0, max: 40, step: 1, default: 12, format: (v) => `${v}/turn` },
    { key: "freqMod", label: "Freq mod", kind: "slider", min: 0, max: 1, step: 0.05, default: 0.5, format: (v) => v.toFixed(2) },
    { key: "compress", label: "Compress", kind: "slider", min: 0, max: 0.9, step: 0.05, default: 0.4, format: (v) => v.toFixed(2) },
    { key: "lineWidth", label: "Weight", kind: "slider", min: 0.3, max: 2, step: 0.1, default: 0.8, format: (v) => v.toFixed(1) },
    { key: "contrast", label: "Contrast", kind: "slider", min: 0.5, max: 2.5, step: 0.1, default: 1.2, format: (v) => v.toFixed(1) },
    { key: "rings", label: "Rings", kind: "toggle", min: 0, max: 1, step: 1, default: 0 },
    { key: "invert", label: "Invert", kind: "toggle", min: 0, max: 1, step: 1, default: 0 },
];

function clamp01(n: number) {
    return n < 0 ? 0 : n > 1 ? 1 : n;
}

function render(input: StrategyInput, params: Record<string, number>): string {
    const { width: W, height: H, sample } = input;

    const spacing = Math.max(2, params.spacing ?? 10);
    const amplitude = params.amplitude ?? 4;
    const frequency = Math.max(0, params.frequency ?? 12);
    const freqMod = params.freqMod ?? 0.5;
    const compress = params.compress ?? 0.4;
    const lineWidth = params.lineWidth ?? 0.8;
    const contrast = params.contrast ?? 1.2;
    const rings = (params.rings ?? 0) > 0.5;
    const invert = (params.invert ?? 0) > 0.5;

    // Darkness in 0..1 where larger = "more ink". Contrast pivots around mid
    // grey; invert flips which side of the tone range reads as dark.
    const darknessAt = (x: number, y: number): number => {
        if (x < 0 || x > W || y < 0 || y > H) return 0;
        let l = sample(x, y);
        l = clamp01(0.5 + (l - 0.5) * contrast);
        if (invert) l = 1 - l;
        return 1 - l;
    };

    // Wind out from the image centre; the farthest corner sets how far to go.
    const cx = W / 2;
    const cy = H / 2;
    const maxR = Math.hypot(Math.max(cx, W - cx), Math.max(cy, H - cy));

    // Marching step along the path: small enough to resolve the wiggle, but
    // bounded so generation stays fast and the SVG compact.
    const step = Math.max(1, Math.min(spacing * 0.4, 2.5));
    // Hard cap on plotted points so an extreme pitch can't explode the file.
    const MAX_POINTS = 60000;

    const stroke = invert ? "#ffffff" : "#111111";

    const marks: string[] = [];

    if (rings) {
        // Stack of closed concentric rings. The pitch between rings compresses
        // with the tone sampled at each ring's start, so dark zones grow denser.
        // A fixed integer cycle count per revolution keeps the wiggle seamless
        // at the seam; only its amplitude tracks local darkness.
        const cycles = Math.max(1, Math.round(frequency));
        let r = spacing;
        let budget = MAX_POINTS;
        while (r <= maxR && budget > 0) {
            const dTheta = step / Math.max(r, step);
            const pts: string[] = [];
            for (let theta = 0; theta < Math.PI * 2; theta += dTheta) {
                const bx = cx + r * Math.cos(theta);
                const by = cy + r * Math.sin(theta);
                const dark = darknessAt(bx, by);
                const rr = r + amplitude * dark * Math.sin(cycles * theta);
                const x = cx + rr * Math.cos(theta);
                const y = cy + rr * Math.sin(theta);
                pts.push(`${x.toFixed(1)},${y.toFixed(1)}`);
            }
            budget -= pts.length;
            if (pts.length > 2) marks.push(`<polygon points="${pts.join(" ")}"/>`);

            const dark = darknessAt(cx + r, cy);
            r += Math.max(2, spacing * (1 - compress * dark));
        }
    } else {
        // One continuous Archimedean-style spiral. Integrate the radius outward:
        // each angular step advances r by the local pitch (compressed in dark
        // zones), so turns pack tighter where the image is dark. The wiggle is a
        // radial offset on top, its phase accumulated so darkness can locally
        // tighten the oscillation (freqMod) without breaking continuity.
        const pitchPerRad = spacing / (Math.PI * 2);
        const pts: string[] = [];
        let r = 0;
        let theta = 0;
        let phase = 0;
        while (r <= maxR && pts.length < MAX_POINTS) {
            const bx = cx + r * Math.cos(theta);
            const by = cy + r * Math.sin(theta);
            const dark = darknessAt(bx, by);

            const rr = r + amplitude * dark * Math.sin(phase);
            const x = cx + rr * Math.cos(theta);
            const y = cy + rr * Math.sin(theta);
            pts.push(`${x.toFixed(1)},${y.toFixed(1)}`);

            const dTheta = step / Math.max(r, step);
            // Cycles per revolution (frequency) tightened locally by darkness.
            phase += frequency * dTheta * (1 + freqMod * dark);
            r += pitchPerRad * dTheta * Math.max(0.1, 1 - compress * dark);
            theta += dTheta;
        }
        if (pts.length > 1) marks.push(`<polyline points="${pts.join(" ")}"/>`);
    }

    return (
        `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}">` +
        `<g stroke="${stroke}" stroke-width="${lineWidth}" stroke-linecap="round" stroke-linejoin="round" fill="none">` +
        marks.join("") +
        `</g></svg>`
    );
}

export const spiralStrategy: Strategy = {
    id: "spiral",
    label: "Concentric Spiral / Rings",
    controls: CONTROLS,
    render,
};
