import type { RequiredDataFromCollectionSlug } from 'payload'

type ProjectSeed = Omit<RequiredDataFromCollectionSlug<'projects'>, 'createdAt' | 'updatedAt' | 'id'>

export const projectsData: ProjectSeed[] = [
    {
        title: 'STRPS — this site',
        slug: 'strps-website-template',
        _status: 'published',
        publishedAt: new Date().toISOString(),
        links: {
            github: 'https://github.com/strps/strps-website-template',
            liveSite: 'https://www.strps.dev',
        },
        techStack: [
            { name: 'Next.js' },
            { name: 'TypeScript' },
            { name: 'PayloadCMS' },
            { name: 'Tailwind CSS' },
            { name: 'PostgreSQL' },
            { name: 'GraphQL' },
            { name: 'Vercel' },
            { name: 'Turborepo' },
        ],
        caseStudy: {
            tag: 'Template / product',
            year: '2024–2026',
            problem: 'Freelance portfolios usually look like a resume with a CSS file.',
            contribution:
                "Built a Next.js + Payload CMS template flexible enough to run a portfolio and a services business from the same codebase — the one you're looking at.",
            context:
                'Most freelance portfolios are a resume with a stylesheet — static, hard to update, and impossible to extend into an actual business tool. I wanted a template I could run my own portfolio on today and turn into a client-facing product later.',
            decisions:
                'Built content as Payload CMS collections from day one (projects, blog posts, and now lab items) rather than hardcoding pages — the same schema that powers my portfolio can power a client\'s site with zero rearchitecting. Framer Motion is used only for a handful of deliberate moments, not blanket page transitions.',
            outcome:
                'The site you\'re looking at right now, and the base template for the web design service I offer clients.',
        },
        content: {
            root: {
                type: 'root',
                children: [
                    {
                        type: 'heading',
                        children: [{ type: 'text', text: 'Overview', version: 1 }],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        tag: 'h2',
                        version: 1,
                    },
                    {
                        type: 'paragraph',
                        children: [
                            {
                                type: 'text',
                                text: 'A modern, full-stack website template built with Next.js 16 and PayloadCMS 3. Designed as a monorepo with Turborepo, it provides a fully customizable portfolio and content management solution with a headless CMS backend and a decoupled frontend.',
                                version: 1,
                            },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                    },
                    {
                        type: 'heading',
                        children: [{ type: 'text', text: 'Features', version: 1 }],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        tag: 'h2',
                        version: 1,
                    },
                    {
                        type: 'list',
                        children: [
                            {
                                type: 'listitem',
                                children: [{ type: 'text', text: 'Headless CMS with PayloadCMS 3 and Lexical rich text editor', version: 1 }],
                                direction: 'ltr',
                                format: '',
                                indent: 0,
                                value: 1,
                                version: 1,
                            },
                            {
                                type: 'listitem',
                                children: [{ type: 'text', text: 'Configurable page sections with drag-and-drop block layout', version: 1 }],
                                direction: 'ltr',
                                format: '',
                                indent: 0,
                                value: 2,
                                version: 1,
                            },
                            {
                                type: 'listitem',
                                children: [{ type: 'text', text: 'Apollo GraphQL client for efficient data fetching', version: 1 }],
                                direction: 'ltr',
                                format: '',
                                indent: 0,
                                value: 3,
                                version: 1,
                            },
                            {
                                type: 'listitem',
                                children: [{ type: 'text', text: 'Dark mode support with automatic theme detection', version: 1 }],
                                direction: 'ltr',
                                format: '',
                                indent: 0,
                                value: 4,
                                version: 1,
                            },
                            {
                                type: 'listitem',
                                children: [{ type: 'text', text: 'SEO-optimized with meta fields and sitemap generation', version: 1 }],
                                direction: 'ltr',
                                format: '',
                                indent: 0,
                                value: 5,
                                version: 1,
                            },
                            {
                                type: 'listitem',
                                children: [{ type: 'text', text: 'Live preview in the admin panel for real-time content editing', version: 1 }],
                                direction: 'ltr',
                                format: '',
                                indent: 0,
                                value: 6,
                                version: 1,
                            },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        listType: 'bullet',
                        start: 1,
                        tag: 'ul',
                        version: 1,
                    },
                    {
                        type: 'heading',
                        children: [{ type: 'text', text: 'Architecture', version: 1 }],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        tag: 'h2',
                        version: 1,
                    },
                    {
                        type: 'paragraph',
                        children: [
                            {
                                type: 'text',
                                text: 'The project follows a monorepo structure managed by pnpm workspaces and Turborepo. The Payload app serves as the CMS backend and admin interface, while the frontend app is a standalone Next.js application that fetches data via GraphQL. Shared types are generated from the Payload schema and consumed by both apps through a shared package.',
                                version: 1,
                            },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                    },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
            },
        },
        appearance: {
            headerOverrides: {
                theme: 'dark',
                background: false,
                overlay: true,
            },
        },
        meta: {
            title: 'STRPS Website Template — Full-Stack Portfolio & CMS',
            description:
                'A modern website template built with Next.js, PayloadCMS, and Tailwind CSS. Features a headless CMS, GraphQL API, dark mode, and SEO optimization.',
        },
    },
    {
        title: 'TrackBit',
        slug: 'trackbit',
        _status: 'published',
        publishedAt: new Date().toISOString(),
        links: {
            github: 'https://github.com/strps/trackbit',
            liveSite: 'https://trackbit.app',
        },
        techStack: [
            { name: 'React' },
            { name: 'TypeScript' },
            { name: 'Node.js' },
            { name: 'Express' },
            { name: 'PostgreSQL' },
            { name: 'Tailwind CSS' },
            { name: 'Drizzle ORM' },
            { name: 'Zustand' },
        ],
        caseStudy: {
            tag: 'Product',
            year: '2025',
            problem:
                'Habit trackers either oversimplify (a checkbox) or overwhelm (spreadsheets nobody keeps up with).',
            contribution:
                'Built a full-stack habit tracker with streak logic, weekly analytics, and a dashboard people actually open twice a day.',
            context:
                'Habit trackers either oversimplify to a checkbox or overwhelm with spreadsheets nobody keeps up with. I wanted something in between — enough structure to see patterns, not enough friction to abandon after a week.',
            decisions:
                'Streaks are computed server-side and cached, not recalculated on every render — the analytics dashboard stayed fast even with a year of daily entries. Chose Postgres over a document store specifically so streak queries could be plain SQL instead of application-layer logic.',
            outcome:
                "A working product with streak tracking, weekly analytics, and a dashboard that's actually opened daily rather than abandoned after onboarding.",
        },
        content: {
            root: {
                type: 'root',
                children: [
                    {
                        type: 'heading',
                        children: [{ type: 'text', text: 'Overview', version: 1 }],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        tag: 'h2',
                        version: 1,
                    },
                    {
                        type: 'paragraph',
                        children: [
                            {
                                type: 'text',
                                text: 'TrackBit is a habit tracking application that helps users build and maintain positive daily routines. With an intuitive interface and insightful analytics, it makes it easy to stay accountable and visualize progress over time.',
                                version: 1,
                            },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                    },
                    {
                        type: 'heading',
                        children: [{ type: 'text', text: 'Features', version: 1 }],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        tag: 'h2',
                        version: 1,
                    },
                    {
                        type: 'list',
                        children: [
                            {
                                type: 'listitem',
                                children: [{ type: 'text', text: 'Create and manage daily, weekly, and custom habits', version: 1 }],
                                direction: 'ltr',
                                format: '',
                                indent: 0,
                                value: 1,
                                version: 1,
                            },
                            {
                                type: 'listitem',
                                children: [{ type: 'text', text: 'Visual streak tracking with calendar heatmaps', version: 1 }],
                                direction: 'ltr',
                                format: '',
                                indent: 0,
                                value: 2,
                                version: 1,
                            },
                            {
                                type: 'listitem',
                                children: [{ type: 'text', text: 'Progress analytics with charts and completion percentages', version: 1 }],
                                direction: 'ltr',
                                format: '',
                                indent: 0,
                                value: 3,
                                version: 1,
                            },
                            {
                                type: 'listitem',
                                children: [{ type: 'text', text: 'Customizable reminders and notifications', version: 1 }],
                                direction: 'ltr',
                                format: '',
                                indent: 0,
                                value: 4,
                                version: 1,
                            },
                            {
                                type: 'listitem',
                                children: [{ type: 'text', text: 'Responsive design that works on desktop and mobile', version: 1 }],
                                direction: 'ltr',
                                format: '',
                                indent: 0,
                                value: 5,
                                version: 1,
                            },
                            {
                                type: 'listitem',
                                children: [{ type: 'text', text: 'User authentication with secure session management', version: 1 }],
                                direction: 'ltr',
                                format: '',
                                indent: 0,
                                value: 6,
                                version: 1,
                            },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        listType: 'bullet',
                        start: 1,
                        tag: 'ul',
                        version: 1,
                    },
                    {
                        type: 'heading',
                        children: [{ type: 'text', text: 'How It Works', version: 1 }],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        tag: 'h2',
                        version: 1,
                    },
                    {
                        type: 'paragraph',
                        children: [
                            {
                                type: 'text',
                                text: 'Users create habits with customizable schedules and goals. Each day, they check off completed habits from their dashboard. TrackBit records completions and calculates streaks, providing visual feedback through heatmaps and charts. The backend uses Drizzle ORM with PostgreSQL for efficient data storage and retrieval, while Zustand manages client-side state for a snappy user experience.',
                                version: 1,
                            },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                    },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
            },
        },
        appearance: {
            headerOverrides: {
                theme: 'dark',
                background: false,
                overlay: true,
            },
        },
        meta: {
            title: 'TrackBit — Habit Tracker',
            description:
                'A habit tracking app built with React, Node.js, and PostgreSQL. Features streak tracking, analytics dashboards, and customizable reminders to help build better routines.',
        },
    },
]
