name: website

services:

  website:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/strps-dev-web:cached
    depends_on:
      - postgres
    command: sleep infinity
    network_mode: host

  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: your-database-name
      POSTGRES_HOST_AUTH_METHOD: trust
    network_mode: host
