name: website

services:

  website:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      POSTGRES_URL: postgresql://127.0.0.1:5432/your-database-name
      PAYLOAD_SECRET: YOUR_SECRET_HERE
      NEXT_PUBLIC_SERVER_URL: http://localhost:3000
      CRON_SECRET: YOUR_CRON_SECRET_HERE
      PREVIEW_SECRET: YOUR_SECRET_HERE
    depends_on:
      - postgres
    network_mode: host


  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: your-database-name
      POSTGRES_HOST_AUTH_METHOD: trust
    network_mode: host
