import type { Media, User } from '@/payload-types'
import { RequiredDataFromCollectionSlug } from 'payload'

export type ProjectArgs = {
  heroImage: Media
  author: User
}

export const project1: (args: ProjectArgs) => RequiredDataFromCollectionSlug<'projects'> = ({
  heroImage,
  author,
}) => {
  return {
    title: 'STRPS Website',
    slug: 'strps-website',
    _status: 'published',
    heroImage: heroImage.id,
    content: {
      root: {
        type: 'root',
        direction: 'ltr',
        format: 'left',
        indent: 0,
        version: 1,
        children: [
          {
            type: 'heading',
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'STRPS Website: Modern CMS-Powered Website',
                version: 1,
              },
            ],
            tag: 'h1',
          },
          {
            type: 'paragraph',
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'STRPS Website is a modern, performance-optimized web application that combines the power of Next.js and PayloadCMS to deliver a beautifully designed, fully customizable content management experience. With responsive UI, block-based content architecture, and secure form handling, STRPS is designed for scalability, flexibility, and top-tier performance.',
                version: 1,
              },
            ],
          },
          {
            type: 'heading',
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Key Features',
                version: 1,
              },
            ],
            tag: 'h2',
          },
          {
            type: 'list',
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            listType: 'bullet',
            children: [
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Next.js App Router Architecture: Uses the latest Next.js features for optimal performance, SEO, and routing.',
                    version: 1,
                  },
                ],
              },
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Custom CMS Blocks: Pages are built from flexible, modular content blocks like Hero, Skills, and Form sections.',
                    version: 1,
                  },
                ],
              },
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Form Builder with reCAPTCHA: Advanced form integration supporting field customization, validation, and anti-spam protection.',
                    version: 1,
                  },
                ],
              },
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Design System: Consistent and responsive UI using Tailwind CSS and shadcn/ui components.',
                    version: 1,
                  },
                ],
              },
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Publication Workflow: Content creators can manage drafts, approvals, and publishing directly in the CMS.',
                    version: 1,
                  },
                ],
              },
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Dark Mode: Built-in support for light/dark mode switching.',
                    version: 1,
                  },
                ],
              },
            ],
          },
          {
            type: 'heading',
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Technologies Used',
                version: 1,
              },
            ],
            tag: 'h2',
          },
          {
            type: 'list',
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            listType: 'bullet',
            children: [
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Frontend: Next.js (App Router), React, Tailwind CSS, shadcn/ui',
                    version: 1,
                  },
                ],
              },
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Backend: PayloadCMS (Node.js, Express-based Headless CMS)',
                    version: 1,
                  },
                ],
              },
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Database: PostgreSQL',
                    version: 1,
                  },
                ],
              },
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Forms: React Hook Form, reCAPTCHA integration',
                    version: 1,
                  },
                ],
              },
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Deployment: Vercel (includes blob storage, environment config)',
                    version: 1,
                  },
                ],
              },
            ],
          },
          {
            type: 'heading',
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'My Role & Contributions',
                version: 1,
              },
            ],
            tag: 'h2',
          },
          {
            type: 'list',
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            listType: 'bullet',
            children: [
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Designed and implemented the custom content block system (Hero, Skills, Form)',
                    version: 1,
                  },
                ],
              },
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Integrated reCAPTCHA for secure form submissions',
                    version: 1,
                  },
                ],
              },
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Built the responsive UI using Tailwind CSS and shadcn/ui components',
                    version: 1,
                  },
                ],
              },
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Configured PayloadCMS collections and publication workflows',
                    version: 1,
                  },
                ],
              },
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Set up deployment pipeline with Vercel and NeonDB',
                    version: 1,
                  },
                ],
              },
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Implemented environment-based configuration for API security, CORS, and authentication',
                    version: 1,
                  },
                ],
              },
            ],
          },
          {
            type: 'heading',
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Key Learnings & Challenges',
                version: 1,
              },
            ],
            tag: 'h2',
          },
          {
            type: 'list',
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            listType: 'bullet',
            children: [
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Gained deep understanding of Next.js App Router and PayloadCMS extensibility',
                    version: 1,
                  },
                ],
              },
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Learned to manage secure user input and prevent spam using server-side reCAPTCHA',
                    version: 1,
                  },
                ],
              },
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Overcame challenges related to dynamic block rendering and CMS-driven routing',
                    version: 1,
                  },
                ],
              },
              {
                type: 'listitem',
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Improved CI/CD setup with environment configuration for cloud deployments',
                    version: 1,
                  },
                ],
              },
            ],
          },
          {
            type: 'paragraph',
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Demo/Screenshots:',
                version: 1,
              },
            ],
          },
          {
            type: 'paragraph',
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '[Image Placeholder: Screenshot of homepage with Hero block]',
                version: 1,
              },
            ],
          },
          {
            type: 'paragraph',
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '[Image Placeholder: Screenshot of CMS block editor interface]',
                version: 1,
              },
            ],
          },
          {
            type: 'paragraph',
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '[Image Placeholder: Screenshot of form submission with reCAPTCHA]',
                version: 1,
              },
            ],
          },
        ],
      },
    },
    meta: {
      title: 'STRPS Website - Modern CMS-Powered Website',
      description:
        'A modern, performance-optimized web application built with Next.js and PayloadCMS, featuring a responsive UI, block-based content architecture, and secure form handling.',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
}
